language: python
python:
    - "2.7"
env:
  - DJANGO_SETTINGS_MODULE='zuhura.settings.testing'
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# safelist
branches:
  only:
  - master
  - ch-write-tests
  
script:
  - cd zuhura
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test
 
after_success:  
  - coveralls
